resource/aws_ebs_snapshot: Support tagging-on-create and in-place `tags` updates (#10935)
Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSEBSSnapshot_tags (45.18s)
--- PASS: TestAccAWSEBSSnapshot_withDescription (50.53s)
--- PASS: TestAccAWSEBSSnapshot_withKms (54.61s)
--- PASS: TestAccAWSEBSSnapshot_basic (56.06s)
```

Output from acceptance testing in AWS GovCloud (US) (unrelated failure due to hardcoded AWS Commerical ARN):

```
--- PASS: TestAccAWSEBSSnapshot_withDescription (30.50s)
--- PASS: TestAccAWSEBSSnapshot_tags (33.01s)
--- PASS: TestAccAWSEBSSnapshot_basic (47.10s)
--- FAIL: TestAccAWSEBSSnapshot_withKms (48.82s)
```